//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖильеНаВыбор
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZilyeEntities : DbContext
    {
        private static ZilyeEntities _context;
        public ZilyeEntities()
            : base("name=ZilyeEntities")
        {
        }
        public static ZilyeEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ZilyeEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Аренда> Аренда { get; set; }
        public virtual DbSet<Квартиры> Квартиры { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
    }
}
