//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЖильеНаВыбор
{
    using System;
    using System.Collections.Generic;
    
    public partial class Квартиры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Квартиры()
        {
            this.Аренда = new HashSet<Аренда>();
        }
    
        public int КодКвартиры { get; set; }
        public string Описание { get; set; }
        public string Этаж { get; set; }
        public string Адрес { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public byte[] Фото { get; set; }
        public string НомерКвартиры { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Аренда> Аренда { get; set; }
    }
}
